name: mobile_app_slb
description: Mobile App Slb
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter_riverpod: ^2.4.10
  localstorage: ^4.0.1+4
  mobile_scanner: ^4.0.1
  qr_scanner_overlay: ^0.0.2
  intl: ^0.18.1
  intl_utils: ^2.8.7
  data_table_2: ^2.5.11
  collection: ^1.18.0
  timezone: ^0.9.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.13

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  image_path_ios: "assets/icon/icon_ios.png"

flutter_native_splash:
  color: "#ffffff"
  ios: true
  android: false
  image: assets/icon/splash.png

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
